services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: graphuser
      POSTGRES_PASSWORD: graphpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: .
    container_name: web
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://graphuser:graphpass@db:5432/graphdb
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app

  tests:
    build:
      context: .
    container_name: tests
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://graphuser:graphpass@db:5432/graphdb_test
    volumes:
      - .:/app
    command: sh -c "pytest -v --disable-warnings --cov=app --cov-report=term-missing --cov-report=html"



volumes:
  pgdata:
