version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: graphdb
      POSTGRES_USER: graphuser
      POSTGRES_PASSWORD: graphpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: web
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://graphuser:graphpass@db:5432/graphdb
    ports:
      - "8000:8000"
    command: >
#      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app

volumes:
  pgdata:
